/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AddNoteLink
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var AddNoteLink = class extends import_obsidian.Plugin {
  async onload() {
    console.log("loading my plugin...");
  }
  async onunload() {
    console.log("unloading my plugin...");
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsibWFpbi50cyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiaW1wb3J0IHsgQXBwLCBFZGl0b3IsIFBsdWdpbiwgU2V0dGluZywgUGx1Z2luU2V0dGluZ1RhYiwgTWFya2Rvd25WaWV3IH0gZnJvbSAnb2JzaWRpYW4nO1xuXG5leHBvcnQgZGVmYXVsdCBjbGFzcyBBZGROb3RlTGluayBleHRlbmRzIFBsdWdpbiB7XG4gICAgYXN5bmMgb25sb2FkKCkge1xuICAgICAgICBjb25zb2xlLmxvZygnbG9hZGluZyBteSBwbHVnaW4uLi4nKTtcbiAgICAgICAgXG4gICAgfVxuXG4gICAgYXN5bmMgb251bmxvYWQoKSB7XG4gICAgICAgIGNvbnNvbGUubG9nKCd1bmxvYWRpbmcgbXkgcGx1Z2luLi4uJyk7XG4gICAgICAgIFxuICAgIH1cbn0iXSwKICAibWFwcGluZ3MiOiAiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUEsc0JBQTZFO0FBRTdFLElBQXFCLGNBQXJCLGNBQXlDLHVCQUFPO0FBQUEsRUFDNUMsTUFBTSxTQUFTO0FBQ1gsWUFBUSxJQUFJLHNCQUFzQjtBQUFBLEVBRXRDO0FBQUEsRUFFQSxNQUFNLFdBQVc7QUFDYixZQUFRLElBQUksd0JBQXdCO0FBQUEsRUFFeEM7QUFDSjsiLAogICJuYW1lcyI6IFtdCn0K
